In [7]:
import numpy as np
from time import time

<h5>Velocidade Numpy x Python</h5>

In [11]:
lista1 = list(range(10**8))

valor=0
inicio = time()
for i in lista1:
    valor += i
fim = time()
print(fim-inicio)

inicio = time()
lista1 = np.array(lista1)
lista1.sum()
fim = time()
print(fim-inicio)


5.480626344680786
3.3809540271759033


<h5>Array e Numpy</h5>

In [19]:
lista = [1,2,3,5,6]
array1 = np.array(lista)

matriz = [[1,2,3],
          [4,5,6]]
array2 = np.array(matriz)

#array com n dimensoes
array3 = np.array(lista, ndmin=5)
print(array3)

[[[[[1 2 3 5 6]]]]]


In [29]:
#range

intervalo = np.arange(0,11,2)
print(intervalo)

#intervalo uniforme
uniforme = np.linspace(0,100,5)
print(uniforme) 

zeros = np.zeros(5)
print(zeros)

matriz_zeros = np.zeros((3,4)) #(3,4) = 3 linhas e 4 colunas
print(matriz_zeros)

matriz_ones = np.ones((3,4)) #(3,4) = 3 linhas e 4 colunas
print(matriz_ones)

[ 0  2  4  6  8 10]
[  0.  25.  50.  75. 100.]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<h5> Atributos Arrays</h5>

In [46]:
#np.dtype() = tipo de item, bool, num etc...

#shape e size (qtd elementos)
array1 = np.array([1,2,3,5])
print(array1.shape, array1.size) 

uns = np.ones((3,4))
print(uns.shape,uns.size)

print(array1.ndim,uns.ndim) #qtd dimensoes

#astype
a = np.array([1.1,2.2,3.3])
b = np.array([1,2,3,4])

array1 = a.astype(int)
array2 = b.astype(float)
print(array1,array2)

(4,) 4
(3, 4) 12
1 2
[1 2 3] [1. 2. 3. 4.]


<h5>Operações com array</h5>

In [56]:
a = np.arange(1,6)
b = np.arange(2,11,2)
print(a,b)

soma = a+b
print(soma)

subtracao = a-b
print(subtracao)

mult = a*b
print(mult)

divisao = b/a
print(divisao)

potencia = a**2
print(potencia)

#escalares
escalar = a-5
print(escalar)



[1 2 3 4 5] [ 2  4  6  8 10]
[ 3  6  9 12 15]
[-1 -2 -3 -4 -5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[ 1  4  9 16 25]
[-4 -3 -2 -1  0]


<h5>Agregação</h5>

In [ ]:
b = np.arange(2,11,2)
print(b)

somainterna = b.sum()
print(somainterna)

c = np.array([[1,2,3],
              [4,5,6]])
somalinha = c.sum(axis=1) #axis=1 é linha
somacoluna = c.sum(axis=0) #axis=0 é coluna
print(somalinha)
print(somacoluna)

media = b.mean()
print(media)

[ 2  4  6  8 10]
30
[ 6 15]
[5 7 9]
6.0


In [ ]:
b = np.arange(2,11,2)
desvio_padrao = b.std()
print(desvio_padrao)

min = b.min()
print(min)
max = b.max()
print(max)

#posicao
indexmin = b.argmin()
indexmax = b.argmax()
print(indexmin)
print(indexmax)


#todos podem receber axis=

2.8284271247461903
2
10
0
4


<h5>Operações Lógicas</h5>

In [73]:
a = np.array([1,2,3,10,12])
b = np.array([1,2,4,12,10])

#vai pegar cada elemento tipo 1==1? 2==2? 3==4?
print(a == b)

#é maior?
print(a>b)

#é menor?
print(a<b)

#> pode tambem ser >= e menor <= tambem

[ True  True False False False]
[False False False False  True]
[False False  True  True False]


In [79]:
aa = np.array([True,False,False,True])
bb = np.array([True,True,False,False])
#tabela verdade da matematica discreta, VV VF etc... & = E
print(aa&bb)

#tabela verdade da matematica discreta, VV VF etc... | = OU
print(aa | bb)

#tabela verdade da matematica discreta ~ = NÃO, muda o sinal da aa
print(~aa)



[ True False False False]
[ True  True False  True]
[False  True  True False]


In [81]:
a = np.arange(-20,50,2)

filtro = a < 0
#menores que 0

print(a[filtro])

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2]


<h5>Indexação e Fatiamento</h5>

In [94]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

#para acesssar elemento de uma matriz é [linha,coluna]

print(a[1,1]) #começa em 0 a coluna e 0 a linha


#fatiamento
b = np.arange(1,11)
print(b)
print(b[3:9:2]) #começa em 4, vai até 9 e pula de 2 em 2

5
[ 1  2  3  4  5  6  7  8  9 10]
[4 6 8]


In [100]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a[:, 0:1]) #pega todas as linhas, da coluna 1 até 2

[[1]
 [4]
 [7]]


<h5>Indexação Booleana</h5>

In [103]:
a = np.arange(0,21)

cond1 = a % 2 == 0
cond2 = a > 12

print(a[cond1 & cond2])

[14 16 18 20]


In [113]:
#Copia

a = np.array([1,2,3,4,5,6])
b = a[0:3]

print(a,b)

b[1:2] = 10
print(a,b)
#assim afeta o original, para não afetar é da seguinte forma

c = a.copy()
print(c)

[1 2 3 4 5 6] [1 2 3]
[ 1 10  3  4  5  6] [ 1 10  3]
[ 1 10  3  4  5  6]


<h5>Manipulação de Formas</h5>

In [119]:
a = np.arange(12)
matriz_3x4 = a.reshape(3,4)
matriz_4x3 = a.reshape(4,3)
matriz_2xx = a.reshape(2,-1) #-1 o numpy decide

print(matriz_2xx)
print(matriz_3x4)
print(matriz_4x3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [136]:
a = np.arange(9)
print(a)
aa = a.reshape(3,3)
print(aa)

aTransposta = aa.T
print(aTransposta) #matriz transposta

aflatten = aa.flatten()
aravel = aa.ravel()

print(aflatten,aravel) #ambos achatam em 1 dimensão

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[0 1 2 3 4 5 6 7 8] [0 1 2 3 4 5 6 7 8]
